# Generated by Django 3.0 on 2019-12-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.FilePathField(path='/img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('characteristic', models.TextField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Tienda_Product',
        ),
    ]
