# Generated by Django 3.0 on 2019-12-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_auto_20191214_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=120),
        ),
    ]
