# Generated by Django 3.0 on 2019-12-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_auto_20191214_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=2000),
        ),
    ]
