# Generated by Django 3.0 on 2019-12-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_auto_20191214_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(path='/../static/img'),
        ),
    ]
